QT += core
QT -= gui

CONFIG += c++11

TARGET = cplusplus11test
CONFIG += console
CONFIG -= app_bundle

# DEFINES += TEST_OVERRIDE_FINAL
#DEFINES += TEST_AUTO_DECLTYPE
#DEFINES += TEST_FOR
DEFINES += TEST_LAMBDA
TEMPLATE = app

SOURCES += main.cpp
